= Building pipleine for your containers

This lab demonstrates Github Actions, which provides the ability to do continuous integration/continuous delivery (CI/CD) from within your Github projects.he lab will lead you through the anatomy of how Github Actions solve this problem. You can apply the same pipeline structure to other CI tools like Concourse or Jenkins.

== Learning Outcomes
After completing the lab, you will be able to:


 . Describe how to create pipeline to deploy an application to AKS
 . Integrate Azure Devops with github.
 . Continuously deploy your code to AKS  
 
=== Set up of AKS
. Create an Azure AKS cluster with 2 nodes in your azure subscription.
. Create a new Azure Devops account and a project namaes Pages in it.
. Create a service connection for your docker registry in Pages project.
. Click on pipeline and start creating your pipeline.

=== Azure Pipeline Creation
. selete source your gitHub repo and authenticate the github connection as required.
. Click on starter pipeline and use the assistant to create the following tasks. You can also copy paste the pipeline yaml from the sample provided below.
  .. gradle task for gradle build
  .. docker task to build and push. Here you would require the service connection created earlier. 
  .. Copy files task to copy **/*.yaml files from DefaultWorkingDirectory to ArtifactStagingDirectory.
  .. kubectl installer task 
  .. kubectl apply task to apply all the yaml files. Here you provide access to your AKS cluster using 'Azure Resource Manager' connection.
  
 
 . Make sure you change the tag in pages-deployment.yaml as per your new docker image tag.
 . The pipeline would look like below
  
+


[source,java]
---------------------------------------------------------------------
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    containerRegistry: '<docker-conn>'
    repository: '<your-docker-id>/<repo-name>'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: <tag-name>
- task: CopyFiles@2
  inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.yaml'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '<Subscription-name>'
    azureResourceGroup: '<your-resource-group>'
    kubernetesCluster: '<k8-cluster-name>'
    useClusterAdmin: true
    namespace: '<your-name>'
    command: 'apply'
    arguments: |
      -f $(Build.ArtifactStagingDirectory)/deployment/pages-namespace.yaml -f $(Build.ArtifactStagingDirectory)/deployment/pages-service.yaml
            -f $(Build.ArtifactStagingDirectory)/deployment/pages-config.yaml
            -f $(Build.ArtifactStagingDirectory)/deployment/pages-deployment.yaml
---------------------------------------------------------------------

. Validate the tag-name and docker-user-name.

. Push your code to git repository and wait till the build starts and deploys to AKS cluster. Verify the AKS cluster to check the deployments and namespaces
