== Putting your container to the Kubernetes cluster

== Learning Outcomes
After completing the lab, you will be able to:

 . Describe how to create Kubernetes Objects
 . Describe how to write yaml files for pods, deployments and services
 . Run your Spring boot application as a docker container
 
== Get started 
Before starting the lab, pull in the kubernetes-start task.
   
   git checkout -b 'lab3' kubernetes-solution
   
As part of this checkout you will get three yaml files - pages-namespace.yaml, pages-services.yaml, pages-deployment.yaml

. Update namespace to your name in pages-namespace.yaml, pages-service.yaml, pages-deployment.yaml.

+

.   Fill in the pages-deployment.yaml
+
[source,java]
---------------------------------------------------------------------
Assign the value pages to app, servicefor and name
Assign proper values for <docker_username>/pages:kube for value of image.
In metadata section add namespace: <your-name>
---------------------------------------------------------------------
. Change type in pages-service.yaml to NodePort
. Build the application and build a docker image
[source,java]
---------------------------------------------------------------------
      ./gradlew clean build
      sudo docker build -t pages .
      sudo docker tag pages <docker_username>/<repo-name>:kube 
      sudo docker push <docker_username>/<repo-name>:kube 
---------------------------------------------------------------------

Instructions for the application to be deployed in minikube for local testing

. minikube and kubectl must be installed in the local machine vm. To start minikube "minikube start" or "minikube start --driver=virtualbox/docker" could be executed in the terminal.
[source,java]
---------------------------------------------------------------------
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
      kubectl version --client
      sudo usermod -aG docker $USER && newgrp docker
---------------------------------------------------------------------
. Try starting minikube
[source,java]
---------------------------------------------------------------------
   minikube start
---------------------------------------------------------------------

. Run the following commands in terminal to run the application in minikube


+
[source,java]
---------------------------------------------------------------------
kubectl -f deployment/pages-namespace.yaml
kubectl -f deployment/pages-service.yaml
kubectl -f deployment/pages-deployment.yaml
---------------------------------------------------------------------  

. The above commands will create a namespace in the name <your-name> and a deployment, service called pages under the same namespace. Verify the namespace, deployment and service are created by using the following command

+
[source,java]
---------------------------------------------------------------------
kubectl get deployment pages --namespace <your-name>
kubectl get service pages --namespace <your-name>
---------------------------------------------------------------------  

. Below command would set your default namespace to the new namespace and we don't need to suffix --namespace in all commands

[source,java]
---------------------------------------------------------------------
kubectl config set-context --current --namespace=<your-name>
---------------------------------------------------------------------  

.   Execute the command "minikube service pages --namespace <your-name>" and it would open the application in the browser.

.   Instructions for the application to be deployed in Enterprise AKS
.. azure cli must have been installed already
.. Execute the below command to login to the AKS
[source, java]
---------------------------------------------------------------------
    $ az login
---------------------------------------------------------------------

+
[source, java, numbered]
---------------------------------------------------------------------
$ az aks get-credentials --resource-group <<ResourceGroup-Name>> --name <<AKSCluster-Name>>
---------------------------------------------------------------------

. Run below command to check if kubectl is pointing to AKS cluster.

[source, java, numbered]
---------------------------------------------------------------------
$ kubectl config get-contexts
---------------------------------------------------------------------
. change the type to LoadBalancer in pages-service.yaml
Now we are good to execute our commands in the AKS cluster

. Execute the below commands to create namespace, deployment and service in aks cluster
+
[source, java, numbered]
---------------------------------------------------------------------
kubectl -f deployment/pages-namespace.yaml
kubectl -f deployment/pages-service.yaml
kubectl -f deployment/pages-deployment.yaml
---------------------------------------------------------------------

. Verify the namespace, deployment and service are created by using the following command in the aks cluster
+ 
[source,java]
---------------------------------------------------------------------
kubectl get deployment pages --namespace <your-name>
kubectl get service pages --namespace <your-name>
---------------------------------------------------------------------

. Below command would set your default namespace to the new namespace and we don't need to suffix --namespace in all commands

+  

[source,java]
---------------------------------------------------------------------
kubectl config set-context --current --namespace=<your-name>
---------------------------------------------------------------------

. Identify the external ip of the pages service from the output of "kubectl get service pages" command.

. Take the external IP address and hit <External-IP>:8080in browser to access application

. Commit your code to your github repository

+

[source,java]
---------------------------------------------------------------------
git add .
git commit -m "commit message"
git push -u origin master 
---------------------------------------------------------------------
