== Putting your container to the Kubernetes cluster

== Learning Outcomes
After completing the lab, you will be able to:

 . Describe how to create Kubernetes Objects
 . Describe how to write yaml files for pods, deployments and services
 . Run your Spring boot application as a docker container
 
== Get started 
Before starting the lab, pull in the kubernetes-start task.
   
   git cherry-pick kubernetes-start
   
As part of this checkout you will get three yaml files - pages-namespace.yaml, pages-services.yaml, pages-deployment.yaml

. Fill in the pages-namespace.yaml as below 

+
[source,java]
---------------------------------------------------------------------
Assign your <first-name> to the name section
---------------------------------------------------------------------

.   Fill in the pages-services.yaml as below


+
[source,java]
---------------------------------------------------------------------
Assign 8080 to targetPort and port
Assign TCP to protocol
Assign the value pages to app, servicefor and name
In metadata section add namespace: <your-name>
---------------------------------------------------------------------

.   Fill in the pages-deployment.yaml
+
[source,java]
---------------------------------------------------------------------
Assign the value pages to app, servicefor and name
Assign proper values for <docker_username>/pages:kube for value of image.
In metadata section add namespace: <your-name>
---------------------------------------------------------------------

In all the above section replace <your-name> with your own first name. 

Instructions for the application to be deployed in minikube for local testing

minikube and kubectl must be installed in the local machine vm. To start minikube "minikube start" or "minikube start --driver=virtualbox/docker" could be executed in the terminal.


. Change type in pages-service.yaml to NodePort

. Run the following commands in terminal to run the application in minikube


+
[source,java]
---------------------------------------------------------------------
kubectl create -f deployment/pages-namespace.yaml
kubectl create -f deployment/pages-service.yaml
kubectl create -f deployment/pages-deployment.yaml
---------------------------------------------------------------------  

. The above commands will create a namespace in the name <your-name> and a deployment, service called pages under the same namespace. Verify the namespace, deployment and service are created by using the following command

+
[source,java]
---------------------------------------------------------------------
kubectl get deployment pages --namespace <your-name>
kubectl get service pages --namespace <your-name>
---------------------------------------------------------------------  

. Below command would set your default namespace to the new namespace and we don't need to suffix --namespace in all commands

[source,java]
---------------------------------------------------------------------
kubectl config set-context --current --namespace=<your-name>

kubectl get pods
---------------------------------------------------------------------  



.   Execute the command "minikube service pages --namespace <your-name>" and it would open the application in the browser or run the curl command if you are using SSH terminal for e.g. curl http://192.168.49.2:32512.

.   Instructions for the application to be deployed in Enterprise AKS
.. azure cli must have been installed already
.. Login into https://portal.azure.com/ and create a resource for kubernetes services 

.. Receive the AKS credential
.. Execute the below command to get credential

---------------------------------------------------------------------
az aks get-credentials --resource-group <<myResourceGroup>> --name <<myAKSCluster>>
---------------------------------------------------------------------


Now we are good to execute our commands in the AKS cluster

. Change type in pages-service.yaml to LoadBalancer

. Execute the below commands to create namespace, deployment and service in aks cluster

---------------------------------------------------------------------
kubectl create -f deployment/pages-namespace.yaml
kubectl create -f deployment/pages-service.yaml
kubectl create -f deployment/pages-deployment.yaml
---------------------------------------------------------------------

. Verify the namespace, deployment and service are created by using the following command in the aks cluster

---------------------------------------------------------------------
kubectl get deployment pages --namespace <your-name>
kubectl get service pages --namespace <your-name>
---------------------------------------------------------------------

. Below command would set your default namespace to the new namespace and we don't need to suffix --namespace in all commands


---------------------------------------------------------------------
kubectl config set-context --current --namespace=<your-name>

kubectl get pods

---------------------------------------------------------------------

. Identify the external ip of the pages service from the output of "kubectl get service pages" command.

. Commit your code to your github repository

+

[source,java]
---------------------------------------------------------------------
git add .
git commit -m "commit message"
git push -u origin master 
---------------------------------------------------------------------



=== Note

If you get GIT merge issue due to behind than the remote branch cherry-pick, in that case you can copy somewhere your deployment folder, then create new branch (cherry-pick) from master and add back to your deployment folder in it. then perform below git operations -

git add .

git commit -m "Commit Message" 

git push origin cherry-pick:master -f 

   