= Building a Spring Boot Application

== Learning Outcomes
After completing the lab, you will be able to:

 . Describe how to create runnable Spring Boot application
 . Describe how to create a controller that responds to HTTP requests
 . Use gradle to run gradle tasks
 
The  https://dell-edu-lab-store.s3.ap-south-1.amazonaws.com/repository/pages.zip[pages] codebase contains a local Git repository with the starting points and the solutions for all the labs in this unit. Download the linked zip file and extract the codebase in the ~/workspace directory.  The extracted directory will contain a single text file as well as the (hidden) Git files. You will be building up the code in this directory bit by bit, and we have provided reference implementations at each stage identified by tags in the Git repository. Take some time to navigate through the tags and branches using the following command: 

   git log --graph --decorate --oneline --all

. open terminal and run:
    sudo apt install unzip
	unzip pages.zip
   
Create a repository called pages in your GitHub account. Add this repository as a remote called origin of your local repository.Keep everything default, while creating the repository, don't change anything other than default. You will push all of your work to this repository during the next few labs.
    git remote add origin <<repo-url>>

We will start by pushing the initial commit to GitHub, complete with the start and solutions tags.

  git push origin master --tags


.   Create the gradle ecosystem by using the following commands

+
[source,java]
---------------------------------------------------------------------
gradle wrapper --gradle-version 6.4.1 --distribution-type all
---------------------------------------------------------------------

.   Create a .gitignore file with following content
+
[source,java]
---------------------------------------------------------------------
HELP.md
.gradle
build/
!gradle/wrapper/gradle-wrapper.jar
!**/src/main/**
!**/src/test/**

### STS ###
.apt_generated
.classpath
.factorypath
.project
.settings
.springBeans
.sts4-cache

### IntelliJ IDEA ###
.idea
*.iws
*.iml
*.ipr
out/

### NetBeans ###
/nbproject/private/
/nbbuild/
/dist/
/nbdist/
/.nb-gradle/

### VS Code ###
.vscode/
---------------------------------------------------------------------
. Git commit and push .gitignore to master
. Checkout the hello-solution tag. This add all the required test classes and main classes to your folder.
    git checkout -b '<branch-name>' hello-solution

. Add actuator dependency to the list of dependencies in build.gradle inside the dependencies closure
+ 
[source,java]
---------------------------------------------------------------------
implementation 'org.springframework.boot:spring-boot-starter-actuator'
---------------------------------------------------------------------

. Add the following in both test and src application.properties
. Add the below content in both the properties files
+  

[source,java]
---------------------------------------------------------------------
spring.application.name=pages
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
---------------------------------------------------------------------

. Build & test the application
+ 

[source,java]
---------------------------------------------------------------------
./gradlew clean build
---------------------------------------------------------------------

. Run the application
+ 

[source,java]
---------------------------------------------------------------------
./gradlew bootRun
---------------------------------------------------------------------

. Access your application
+

[source,java]
---------------------------------------------------------------------
Browse to http://localhost:8080
---------------------------------------------------------------------

. Commit your code to your github repository

+

[source,java]
---------------------------------------------------------------------
git add .
git commit -m "commit message"
git push origin <branch-name>:master -f
---------------------------------------------------------------------
